.TH configurejamie 1  "March 27, 2011" "v0.8" "USER COMMANDS"
.SH NAME
configurejamie \- designate master and slave computers using IP's and NFS
.SH SYNOPSIS
.\" The master command
.B configurejamie
.IR master
.br
.B configurejamie
.IR slave
.IR MASTER_IP
.SH DESCRIPTION
This command is used to assist in the creation of Clustered Computing, 
using TCP/IP connections and NFS mounting. 
.SH OPTIONS
.TP
.BI master
designates running machine as a master computer in the cluster
.TP
.BI slave
designates the running machine as a slave computer in a cluster. Must be followed by
.IR MASTER_IP

.TP
.BI MASTER_IP
The IP printed when
.I configurejamie master
is issued on the master computer in the cluster.
.PP
.SH AUTHORS
Programmed by James Church and John Stitt
.br
Man page by Alex Conrey
.SH SEE ALSO
mount(1) ifconfig(1) ssh(1)
